packagegroup-fsl-gstreamer1.0: follow meta-freescale changes to imx-gst1.0-plugin
Commit 25c0c7d34a60 ("gst/gstreamer: Bump 1.26.0 -> 1.26.6") in
meta-freescale removed the packages imx-gst1.0-plugin-gplay and
imx-gst1.0-plugin-grecorder and merged them together with some other
tools into imx-gst1.0-plugin-tools.

Replace these packages with imx-gst1.0-plugin-tools.

Fixes the following build error:
ERROR: Nothing RPROVIDES 'imx-gst1.0-plugin-grecorder' (but [...]/layers/meta-freescale-distro/recipes-fsl/packagegroups/packagegroup-fsl-gstreamer1.0.bb RDEPENDS on or otherwise requires it)

Signed-off-by: Ernest Van Hoecke <ernest.vanhoecke@toradex.com>