half: Fix S = WORKDIR reference
Setting `S = ${WORKDIR}` is no longer allowed. Use the the default
setting of S and move the sources accordingly.
Compare wit OE-core commit 32cba1cc91 ("insane: Error for S == WORKDIR")

Fixes:
ERROR: <xyz>.bb: Using S = ${WORKDIR} is no longer supported

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>