gli: backport upstream patches to resolve gcc11 build
According to the GCC11 Porting Guide [1], error is issued on ordered
pointer comparison with integer which causes the following build
failure:

| test/core/core_convert.cpp:35:85: error: ordered comparison of pointer with integer zero ('const char*' and 'int')
|    35 |         if(std::strstr(FilenameDst, ".dds") > 0 || std::strstr(FilenameDst, ".ktx") > 0)
|       |                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~

Backport upstream patch to correct the ordered comparison.

Link: [1] https://gcc.gnu.org/gcc-11/porting_to.html
Signed-off-by: Andrey Zhizhikin <andrey.z@gmail.com>