fsl-gpu-sdk: Add missing dependency on xrandr for X11 backend
When building against X11 backend, xrandr is required. The dependency
was not explicit so it was causing following failure:

Log data follows:
| DEBUG: Executing shell function do_compile
| make: Nothing to be done for 'all'.
| make: Nothing to be done for 'all'.
| make: Nothing to be done for 'all'.
| arm-oel-linux-gnueabi-g++  ... -c source/FslGraphicsEGL/Window/X11/EGLNativeWindowX11.cpp
| source/FslGraphicsEGL/Window/X11/EGLNativeWindowX11.cpp:39:35: fatal error: X11/extensions/Xrandr.h: No such file or directory
|  #include <X11/extensions/Xrandr.h>
|                                    ^
| compilation terminated.
| GNUmakefile_Yocto:139: recipe for target 'obj/Yocto_X11/Release/source/FslGraphicsEGL/Window/X11/EGLNativeWindowX11.o' failed
| make: *** [obj/Yocto_X11/Release/source/FslGraphicsEGL/Window/X11/EGLNativeWindowX11.o] Error 1
| WARNING: exit code 2 from a shell command.
| ERROR: Function failed: do_compile (log file is located at .../tmp/work/cortexa9hf-vfp-neon-mx6sx-oel-linux-gnueabi/fsl-gpu-sdk/2.0-r0/temp/log.do_compile.14664)

Change-Id: I07ec9e025762d544c37ced914a28da209a9ab6b7
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>